### ISSUE TITLE
feature request: add arbitrary arguments to build command

### ISSUE THREAD

**Issue by magnetophon** [Frando/rust-faust#23]
The faust compiler has a whole slew of useful command line arguments.
For example ``-t 0`` makes sure the compiler doesn't time-out, or ``-vec`` tries to generate easy to vectorize code.

So, a ``.with_arg()`` method for ``FaustBuilder::new`` would be very handy.

The project I'm working on will often time-out while compiling, so currently I'm using a local checkout of ``rust-faust`` where I added:
```rust
.arg("-t")
 .arg("0")
 ```
 to [lib.rs](https://github.com/Frando/rust-faust/blob/main/faust-build/src/lib.rs#L61).

**Comment by obsoleszenz** [comment]
See https://github.com/Frando/rust-faust/pull/25
